name: Run Unit Tests on PR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, ci_testing ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore Dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
      # set pr number, if it's a pr build
    - name: Set PR Build Number
      id: PRNUMBER
      if: ${{ github.event_name == 'pull_request' }}
      uses: kkak10/pr-number-action@v1.3

      # set report file and title 
    - name: Set Test Title
      run: | 
            if ${{ github.event_name == 'pull_request' }}
            then
              echo "run_title=Test_Run_for_PR_#${{steps.PRNUMBER.outputs.pr}}_(${{github.run_number}})" >> $GITHUB_ENV
              echo "file_name=TestReport_${{steps.PRNUMBER.outputs.pr}}_${{github.run_number}}"  >> $GITHUB_ENV
            else
              echo "run_title=Test_Run_${{github.run_number}}" >> $GITHUB_ENV
              echo "file_name=TestReport_${{github.run_number}}" >> $GITHUB_ENV
            fi
            
    - name: Test Bemby.AccountModule.Api
      run: dotnet test ./tests/Bemby.AccountModule.Api.Tests/Bemby.AccountModule.Api.Tests.csproj --no-restore --no-build --logger:"liquid.md;LogFileName=${{github.workspace}}/${{env.file_name}}_Bemby.AccountModule.Api;Title=${{env.run_title}}_Bemby.AccountModule.Api.md;"

    - name: Test Bemby.AccountModule.Application
      run: dotnet test ./tests/Bemby.AccountModule.Application.Tests/Bemby.AccountModule.Application.Tests.csproj --no-restore --no-build --logger:"liquid.md;LogFileName=${{github.workspace}}/${{env.file_name}}_Bemby.AccountModule.Application;Title=${{env.run_title}}_Bemby.AccountModule.Application.md;"
    
    - name: Test Bemby.AccountModule.Application.Interfaces
      run: dotnet test ./AccountModule/tests/Bemby.AccountModule.Application.Interfaces.Tests/Bemby.AccountModule.Application.Interfaces.Tests.csproj --no-restore --no-build --logger:"liquid.md;LogFileName=${{github.workspace}}/${{env.file_name}}_Bemby.AccountModule.Application.Interfaces;Title=${{env.run_title}}_Bemby.AccountModule.Application.Interfaces.md;"
    
    - name: Test Bemby.AccountModule.Domain
      run: dotnet test ./AccountModule/tests/Bemby.AccountModule.Domain.Tests/Bemby.AccountModule.Domain.Tests.csproj --no-restore --no-build --logger:"liquid.md;LogFileName=${{github.workspace}}/${{env.file_name}}_Bemby.AccountModule.Domain;Title=${{env.run_title}}_Bemby.AccountModule.Domain.md;"

    - name: Test Bemby.AccountModule.Infrastructure
      run: dotnet test ./AccountModule/tests/Bemby.AccountModule.Infrastructure.Tests/Bemby.AccountModule.Infrastructure.Tests.csproj --no-restore --no-build --logger:"liquid.md;LogFileName=${{github.workspace}}/${{env.file_name}}_Bemby.AccountModule.Domain;Title=${{env.run_title}}_Bemby.AccountModule.Infrastructure.md;"
    
    # upload report as build artifact
    - name: Upload Bemby.AccountModule.Api Test Report as a Build Artifact
      uses: actions/upload-artifact@v2
      if: ${{always()}}
      with:
        name: 'Bemby.AccountModule.Api Test Run'
        path: "${{github.workspace}}/${{env.file_name}}_Bemby.AccountModule.Api.md"

    - name: Upload Bemby.AccountModule.Api Test Report as a Build Artifact
      uses: actions/upload-artifact@v2
      if: ${{always()}}
      with:
        name: 'Bemby.AccountModule.Application Test Run'
        path: "${{github.workspace}}/${{env.file_name}}_Bemby.AccountModule.Application.md"

    - name: Upload Bemby.AccountModule.Api Test Report as a Build Artifact
      uses: actions/upload-artifact@v2
      if: ${{always()}}
      with:
        name: 'Bemby.AccountModule.Application.Interfaces Test Run'
        path: "${{github.workspace}}/${{env.file_name}}_Bemby.AccountModule.Application.Interfaces.md"

    - name: UploadBemby.AccountModule.Domain Test Report as a Build Artifact
      uses: actions/upload-artifact@v2
      if: ${{always()}}
      with:
        name: 'Bemby.AccountModule.Domain Test Run'
        path: "${{github.workspace}}/${{env.file_name}}_Bemby.AccountModule.Domain.md"
        
    - name: Upload Bemby.AccountModule.Api Test Report as a Build Artifact
      uses: actions/upload-artifact@v2
      if: ${{always()}}
      with:
        name: 'Bemby.Bemby.AccountModule.Infrastructure Test Run'
        path: "${{github.workspace}}/${{env.file_name}}_Bemby.AccountModule.Infrastructure.md"

    - name: Comment Bemby.AccountModule.Api Test Results on PR
      uses: machine-learning-apps/pr-comment@master
      if: ${{ github.event_name == 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: "${{ env.file_name }}_Bemby.AccountModule.Api.md"
        
    - name: Comment Bemby.AccountModule.Application Test Results on PR
      uses: machine-learning-apps/pr-comment@master
      if: ${{ github.event_name == 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: "${{ env.file_name }}_Bemby.AccountModule.Application.md"
        
    - name: Comment Bemby.AccountModule.Application.Interfaces Test Results on PR
      uses: machine-learning-apps/pr-comment@master
      if: ${{ github.event_name == 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: "${{ env.file_name }}_Bemby.AccountModule.Application.Interfaces.md"
        
    - name: Comment Bemby.AccountModule.Domain Test Results on PR
      uses: machine-learning-apps/pr-comment@master
      if: ${{ github.event_name == 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: "${{ env.file_name }}_Bemby.AccountModule.Domain.md"
        
    - name: Comment Bemby.AccountModule.Infrastructure Test Results on PR
      uses: machine-learning-apps/pr-comment@master
      if: ${{ github.event_name == 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: "${{ env.file_name }}_Bemby.AccountModule.Infrastructure.md"
        
        
